[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
port = 8501
address = "0.0.0.0"
headless = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "viewer"